# A versioned service release: runtime image + baked release manifest + OCI labels.
ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}
ARG SERVICE
ARG VERSION
ARG REVISION=unknown
ARG CREATED=unknown
ARG RELEASE_JSON
LABEL org.opencontainers.image.title="${SERVICE}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.revision="${REVISION}" \
      org.opencontainers.image.created="${CREATED}" \
      org.opencontainers.image.vendor="GridCast reference estate" \
      org.opencontainers.image.source="https://github.com/soloshun/lumis-cookbooks"
RUN echo "${RELEASE_JSON}" > /app/release.json
