"""Initial GridCast schema, schema comments and least-privilege grants.

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 23:56:00.850571
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


SCHEMAS = {
    "ref": "Reference data: zones, weather stations, vendors",
    "raw": "Vendor data exactly as ingested",
    "features": "Model inputs built per forecast run",
    "ml": "Model registry, forecast runs and forecasts",
    "quality": "Data-quality checks and forecast validation decisions",
    "planning": "Dispatch plans published to grid operators",
}

# role -> (schemas with read access, schemas with write access)
GRANTS = {
    "gridcast_ingest": (["ref"], ["raw"]),
    "gridcast_app": (["ref", "raw"], ["features", "ml"]),
    "gridcast_planning": (["ref", "raw", "ml", "quality"], ["planning"]),
    "gridcast_pipeline": (["ref", "raw", "features", "ml", "planning"], ["quality"]),
    "gridcast_readonly": (list(SCHEMAS), []),
}


def _grants() -> None:
    for role, (read, write) in GRANTS.items():
        for schema in {*read, *write}:
            op.execute(f"GRANT USAGE ON SCHEMA {schema} TO {role}")
        for schema in read:
            op.execute(f"GRANT SELECT ON ALL TABLES IN SCHEMA {schema} TO {role}")
            op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} GRANT SELECT ON TABLES TO {role}")
        for schema in write:
            op.execute(
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {schema} TO {role}"
            )
            op.execute(f"GRANT USAGE ON ALL SEQUENCES IN SCHEMA {schema} TO {role}")
            op.execute(
                f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} "
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {role}"
            )
            op.execute(
                f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} GRANT USAGE ON SEQUENCES TO {role}"
            )


def upgrade() -> None:
    for schema, comment in SCHEMAS.items():
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
        op.execute(f"COMMENT ON SCHEMA {schema} IS '{comment}'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_runs',
    sa.Column('feature_run_id', sa.UUID(), nullable=False, comment='Feature run id'),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False, comment='Information cut-off: no data after this instant is used'),
    sa.Column('horizon_hours', sa.SmallInteger(), nullable=False, comment='Hours ahead covered'),
    sa.Column('status', sa.Text(), nullable=False, comment='running / completed / failed'),
    sa.Column('builder_version', sa.Text(), nullable=False, comment='feature-service version'),
    sa.Column('lag_resolution', sa.Text(), nullable=False, comment='Resolution used for lag features'),
    sa.Column('rows', sa.Integer(), nullable=True, comment='Feature rows produced'),
    sa.Column('db_queries', sa.Integer(), nullable=True, comment='Database queries issued while building'),
    sa.Column('duration_ms', sa.Double(), nullable=True, comment='Build wall-clock time (ms)'),
    sa.Column('error', sa.Text(), nullable=True, comment='Failure summary'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation time'),
    sa.PrimaryKeyConstraint('feature_run_id', name=op.f('pk_feature_runs')),
    schema='features',
    comment='One feature build per forecast cycle'
    )
    op.create_index(op.f('ix_feature_runs_created_at'), 'feature_runs', ['created_at'], unique=False, schema='features')
    op.create_table('models',
    sa.Column('model_name', sa.Text(), nullable=False, comment='Registered model name'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Monotonic version'),
    sa.Column('algorithm', sa.Text(), nullable=False, comment='Estimator family'),
    sa.Column('profile', sa.Text(), nullable=False, comment='Training profile (standard / hifi)'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Hyper-parameters'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Holdout evaluation metrics'),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ordered model inputs'),
    sa.Column('artifact_uri', sa.Text(), nullable=False, comment='s3:// URI of the serialized model'),
    sa.Column('artifact_bytes', sa.BigInteger(), nullable=True, comment='Artifact size'),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=False, comment='First training timestamp'),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=False, comment='Last training timestamp'),
    sa.Column('data_source', sa.Text(), nullable=False, comment='Weather source used for training'),
    sa.Column('created_by', sa.Text(), nullable=False, comment='Who/what trained the model'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation time'),
    sa.PrimaryKeyConstraint('model_name', 'version', name=op.f('pk_models')),
    schema='ml',
    comment='Model registry: every trained model version'
    )
    op.create_table('check_results',
    sa.Column('check_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Result id'),
    sa.Column('pipeline_run_id', sa.Text(), nullable=True, comment='Orchestrator (Prefect) flow run id'),
    sa.Column('subject', sa.Text(), nullable=False, comment='Dataset or artifact checked'),
    sa.Column('check_name', sa.Text(), nullable=False, comment='Check identifier'),
    sa.Column('status', sa.Text(), nullable=False, comment='pass / warn / fail'),
    sa.Column('observed', sa.Double(), nullable=True, comment='Observed value'),
    sa.Column('threshold', sa.Double(), nullable=True, comment='Threshold applied'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Structured context'),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Evaluation time'),
    sa.PrimaryKeyConstraint('check_id', name=op.f('pk_check_results')),
    schema='quality',
    comment='Every data-quality and forecast-validation check'
    )
    op.create_index(op.f('ix_check_results_check_name_checked_at'), 'check_results', ['check_name', 'checked_at'], unique=False, schema='quality')
    op.create_table('ingestion_batches',
    sa.Column('batch_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Batch id'),
    sa.Column('dataset', sa.Text(), nullable=False, comment='weather_observations / weather_forecasts / demand'),
    sa.Column('source', sa.Text(), nullable=False, comment='Vendor or system the batch came from'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Batch start'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Batch end'),
    sa.Column('rows', sa.Integer(), server_default='0', nullable=False, comment='Rows written'),
    sa.Column('status', sa.Text(), nullable=False, comment='ok / error'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error summary when status = error'),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_ingestion_batches')),
    schema='raw',
    comment='Audit trail of every ingestion batch'
    )
    op.create_index(op.f('ix_ingestion_batches_dataset_started_at'), 'ingestion_batches', ['dataset', 'started_at'], unique=False, schema='raw')
    op.create_table('weather_providers',
    sa.Column('provider_id', sa.Text(), nullable=False, comment='Vendor identifier'),
    sa.Column('name', sa.Text(), nullable=False, comment='Vendor name'),
    sa.Column('priority', sa.SmallInteger(), nullable=False, comment='1 = primary, higher = fallback'),
    sa.PrimaryKeyConstraint('provider_id', name=op.f('pk_weather_providers')),
    schema='ref',
    comment='External weather data vendors'
    )
    op.create_table('weather_stations',
    sa.Column('station_id', sa.Text(), nullable=False, comment='Station identifier'),
    sa.Column('name', sa.Text(), nullable=False, comment='Human-readable name'),
    sa.Column('latitude', sa.Double(), nullable=False, comment='WGS84 latitude'),
    sa.Column('longitude', sa.Double(), nullable=False, comment='WGS84 longitude'),
    sa.Column('elevation_m', sa.Double(), nullable=False, comment='Elevation above sea level (m)'),
    sa.PrimaryKeyConstraint('station_id', name=op.f('pk_weather_stations')),
    schema='ref',
    comment='Weather stations whose conditions drive zone demand'
    )
    op.create_table('forecast_runs',
    sa.Column('forecast_run_id', sa.UUID(), nullable=False, comment='Forecast run id'),
    sa.Column('feature_run_id', sa.UUID(), nullable=False, comment='Inputs used'),
    sa.Column('model_name', sa.Text(), nullable=False, comment='Model used'),
    sa.Column('model_version', sa.Integer(), nullable=False, comment='Model version used'),
    sa.Column('status', sa.Text(), nullable=False, comment='completed / failed'),
    sa.Column('rows', sa.Integer(), nullable=True, comment='Forecast rows'),
    sa.Column('inference_ms', sa.Double(), nullable=True, comment='Model inference time (ms)'),
    sa.Column('server_version', sa.Text(), nullable=False, comment='forecast-service version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation time'),
    sa.ForeignKeyConstraint(['feature_run_id'], ['features.feature_runs.feature_run_id'], name=op.f('fk_forecast_runs_feature_run_id_feature_runs')),
    sa.ForeignKeyConstraint(['model_name', 'model_version'], ['ml.models.model_name', 'ml.models.version'], name=op.f('fk_forecast_runs_model_name_models')),
    sa.PrimaryKeyConstraint('forecast_run_id', name=op.f('pk_forecast_runs')),
    schema='ml',
    comment='One model inference per forecast cycle'
    )
    op.create_index(op.f('ix_forecast_runs_created_at'), 'forecast_runs', ['created_at'], unique=False, schema='ml')
    op.create_table('model_aliases',
    sa.Column('model_name', sa.Text(), nullable=False, comment='Registered model'),
    sa.Column('alias', sa.Text(), nullable=False, comment='production / staging / champion ...'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version the alias points to'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last alias change'),
    sa.Column('updated_by', sa.Text(), nullable=False, comment='Actor that moved the alias'),
    sa.ForeignKeyConstraint(['model_name', 'version'], ['ml.models.model_name', 'ml.models.version'], name=op.f('fk_model_aliases_model_name_models')),
    sa.PrimaryKeyConstraint('model_name', 'alias', name=op.f('pk_model_aliases')),
    schema='ml',
    comment='Mutable pointers (e.g. production) into the registry'
    )
    op.create_table('model_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Event id'),
    sa.Column('model_name', sa.Text(), nullable=False, comment='Registered model'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Model version'),
    sa.Column('event', sa.Text(), nullable=False, comment='registered / alias_set'),
    sa.Column('alias', sa.Text(), nullable=True, comment='Alias affected, if any'),
    sa.Column('previous_version', sa.Integer(), nullable=True, comment='Version the alias pointed to before'),
    sa.Column('actor', sa.Text(), nullable=False, comment='Who made the change'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Change description'),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Event time'),
    sa.ForeignKeyConstraint(['model_name', 'version'], ['ml.models.model_name', 'ml.models.version'], name=op.f('fk_model_events_model_name_models')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_model_events')),
    schema='ml',
    comment='Append-only history of registry changes'
    )
    op.create_index(op.f('ix_model_events_at'), 'model_events', ['at'], unique=False, schema='ml')
    op.create_table('weather_forecasts',
    sa.Column('station_id', sa.Text(), nullable=False, comment='Forecast location'),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False, comment='Vendor forecast issue time'),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False, comment='Hour the forecast is valid for'),
    sa.Column('provider_id', sa.Text(), nullable=False, comment='Vendor that issued the forecast'),
    sa.Column('temperature_c', sa.Double(), nullable=False, comment='Air temperature at 2 m (degC)'),
    sa.Column('relative_humidity_pct', sa.Double(), nullable=False, comment='Relative humidity at 2 m (%)'),
    sa.Column('cloud_cover_pct', sa.Double(), nullable=False, comment='Total cloud cover (%)'),
    sa.Column('wind_speed_ms', sa.Double(), nullable=False, comment='Wind speed at 10 m (m/s)'),
    sa.Column('shortwave_radiation_wm2', sa.Double(), nullable=False, comment='Global horizontal irradiance (W/m2)'),
    sa.Column('precipitation_mm', sa.Double(), nullable=False, comment='Precipitation over the interval (mm)'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When GridCast stored the row'),
    sa.ForeignKeyConstraint(['provider_id'], ['ref.weather_providers.provider_id'], name=op.f('fk_weather_forecasts_provider_id_weather_providers')),
    sa.ForeignKeyConstraint(['station_id'], ['ref.weather_stations.station_id'], name=op.f('fk_weather_forecasts_station_id_weather_stations')),
    sa.PrimaryKeyConstraint('station_id', 'issued_at', 'valid_at', name=op.f('pk_weather_forecasts')),
    schema='raw',
    comment='Hourly vendor weather forecasts (one row per issue/valid pair)'
    )
    op.create_index(op.f('ix_weather_forecasts_station_id_valid_at_issued_at'), 'weather_forecasts', ['station_id', 'valid_at', 'issued_at'], unique=False, schema='raw')
    op.create_table('weather_observations',
    sa.Column('station_id', sa.Text(), nullable=False, comment='Observing station'),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False, comment='Observation timestamp reported by the vendor'),
    sa.Column('provider_id', sa.Text(), nullable=False, comment='Vendor that supplied the observation'),
    sa.Column('temperature_c', sa.Double(), nullable=False, comment='Air temperature at 2 m (degC)'),
    sa.Column('relative_humidity_pct', sa.Double(), nullable=False, comment='Relative humidity at 2 m (%)'),
    sa.Column('cloud_cover_pct', sa.Double(), nullable=False, comment='Total cloud cover (%)'),
    sa.Column('wind_speed_ms', sa.Double(), nullable=False, comment='Wind speed at 10 m (m/s)'),
    sa.Column('shortwave_radiation_wm2', sa.Double(), nullable=False, comment='Global horizontal irradiance (W/m2)'),
    sa.Column('precipitation_mm', sa.Double(), nullable=False, comment='Precipitation over the interval (mm)'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When GridCast stored the row'),
    sa.ForeignKeyConstraint(['provider_id'], ['ref.weather_providers.provider_id'], name=op.f('fk_weather_observations_provider_id_weather_providers')),
    sa.ForeignKeyConstraint(['station_id'], ['ref.weather_stations.station_id'], name=op.f('fk_weather_observations_station_id_weather_stations')),
    sa.PrimaryKeyConstraint('station_id', 'observed_at', name=op.f('pk_weather_observations')),
    schema='raw',
    comment='5-minute weather observations as received from vendors'
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.Text(), nullable=False, comment='Load zone identifier'),
    sa.Column('name', sa.Text(), nullable=False, comment='Human-readable name'),
    sa.Column('station_id', sa.Text(), nullable=False, comment='Representative weather station'),
    sa.Column('base_load_mw', sa.Double(), nullable=False, comment='Nominal base load (MW)'),
    sa.Column('cooling_mw_per_degc', sa.Double(), nullable=False, comment='Cooling load sensitivity'),
    sa.Column('rooftop_solar_mw', sa.Double(), nullable=False, comment='Behind-the-meter solar capacity'),
    sa.ForeignKeyConstraint(['station_id'], ['ref.weather_stations.station_id'], name=op.f('fk_zones_station_id_weather_stations')),
    sa.PrimaryKeyConstraint('zone_id', name=op.f('pk_zones')),
    schema='ref',
    comment='Load zones of the synthetic national grid'
    )
    op.create_table('forecast_features',
    sa.Column('feature_run_id', sa.UUID(), nullable=False, comment='Owning feature run'),
    sa.Column('zone_id', sa.Text(), nullable=False, comment='Zone'),
    sa.Column('target_ts', sa.DateTime(timezone=True), nullable=False, comment='Hour being forecast'),
    sa.Column('horizon_h', sa.SmallInteger(), nullable=False, comment='Hours between as_of and target'),
    sa.Column('temperature_c', sa.Double(), nullable=False, comment='Forecast air temperature at 2 m (degc)'),
    sa.Column('relative_humidity_pct', sa.Double(), nullable=False, comment='Forecast relative humidity at 2 m (%)'),
    sa.Column('cloud_cover_pct', sa.Double(), nullable=False, comment='Forecast total cloud cover (%)'),
    sa.Column('wind_speed_ms', sa.Double(), nullable=False, comment='Forecast wind speed at 10 m (m/s)'),
    sa.Column('shortwave_radiation_wm2', sa.Double(), nullable=False, comment='Forecast global horizontal irradiance (w/m2)'),
    sa.Column('precipitation_mm', sa.Double(), nullable=False, comment='Forecast precipitation over the interval (mm)'),
    sa.Column('hour', sa.SmallInteger(), nullable=False, comment='Hour of day (UTC)'),
    sa.Column('dow', sa.SmallInteger(), nullable=False, comment='Day of week (0 = Monday)'),
    sa.Column('is_holiday', sa.Boolean(), nullable=False, comment='Public holiday flag'),
    sa.Column('load_lag_24h', sa.Double(), nullable=False, comment='Mean load same hour yesterday (MW)'),
    sa.Column('load_lag_168h', sa.Double(), nullable=False, comment='Mean load same hour last week (MW)'),
    sa.Column('load_mean_24h', sa.Double(), nullable=False, comment='Mean load over 24 h before as_of'),
    sa.Column('load_recent_3h', sa.Double(), nullable=False, comment='Mean load over 3 h before as_of'),
    sa.ForeignKeyConstraint(['feature_run_id'], ['features.feature_runs.feature_run_id'], name=op.f('fk_forecast_features_feature_run_id_feature_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['ref.zones.zone_id'], name=op.f('fk_forecast_features_zone_id_zones')),
    sa.PrimaryKeyConstraint('feature_run_id', 'zone_id', 'target_ts', name=op.f('pk_forecast_features')),
    schema='features',
    comment='Model inputs for each zone and target hour'
    )
    op.create_table('forecasts',
    sa.Column('forecast_run_id', sa.UUID(), nullable=False, comment='Owning forecast run'),
    sa.Column('zone_id', sa.Text(), nullable=False, comment='Zone'),
    sa.Column('target_ts', sa.DateTime(timezone=True), nullable=False, comment='Forecast hour'),
    sa.Column('horizon_h', sa.SmallInteger(), nullable=False, comment='Hours ahead'),
    sa.Column('load_mw_p50', sa.Double(), nullable=False, comment='Median forecast load (MW)'),
    sa.Column('load_mw_p10', sa.Double(), nullable=False, comment='10th percentile (MW)'),
    sa.Column('load_mw_p90', sa.Double(), nullable=False, comment='90th percentile (MW)'),
    sa.CheckConstraint('load_mw_p10 <= load_mw_p90', name=op.f('ck_forecasts_quantiles_ordered')),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['ml.forecast_runs.forecast_run_id'], name=op.f('fk_forecasts_forecast_run_id_forecast_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['ref.zones.zone_id'], name=op.f('fk_forecasts_zone_id_zones')),
    sa.PrimaryKeyConstraint('forecast_run_id', 'zone_id', 'target_ts', name=op.f('pk_forecasts')),
    schema='ml',
    comment='Hourly probabilistic load forecasts'
    )
    op.create_index(op.f('ix_forecasts_zone_id_target_ts'), 'forecasts', ['zone_id', 'target_ts'], unique=False, schema='ml')
    op.create_table('dispatch_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False, comment='Plan id'),
    sa.Column('forecast_run_id', sa.UUID(), nullable=False, comment='Forecast the plan is based on'),
    sa.Column('status', sa.Text(), nullable=False, comment='active / superseded'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False, comment='First planned hour'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False, comment='Last planned hour'),
    sa.Column('total_energy_mwh', sa.Double(), nullable=False, comment='Planned energy over the horizon'),
    sa.Column('peak_load_mw', sa.Double(), nullable=False, comment='System peak in the plan'),
    sa.Column('published_by', sa.Text(), nullable=False, comment='Publishing pipeline run'),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Publication time'),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['ml.forecast_runs.forecast_run_id'], name=op.f('fk_dispatch_plans_forecast_run_id_forecast_runs')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_dispatch_plans')),
    schema='planning',
    comment='Day-ahead dispatch plans consumed by grid operators'
    )
    op.create_index(op.f('ix_dispatch_plans_published_at'), 'dispatch_plans', ['published_at'], unique=False, schema='planning')
    op.create_table('forecast_validations',
    sa.Column('validation_id', sa.UUID(), nullable=False, comment='Validation id'),
    sa.Column('forecast_run_id', sa.UUID(), nullable=False, comment='Forecast validated'),
    sa.Column('pipeline_run_id', sa.Text(), nullable=True, comment='Orchestrator flow run id'),
    sa.Column('decision', sa.Text(), nullable=False, comment='publish / hold'),
    sa.Column('failed_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Names of failing checks'),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Names of warning checks'),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Decision time'),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['ml.forecast_runs.forecast_run_id'], name=op.f('fk_forecast_validations_forecast_run_id_forecast_runs')),
    sa.PrimaryKeyConstraint('validation_id', name=op.f('pk_forecast_validations')),
    schema='quality',
    comment='Publish/hold gate decisions for each forecast'
    )
    op.create_table('demand_readings',
    sa.Column('zone_id', sa.Text(), nullable=False, comment='Load zone'),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False, comment='Start of the one-minute interval'),
    sa.Column('load_mw', sa.Double(), nullable=False, comment='Average zone load over the minute (MW)'),
    sa.Column('quality', sa.Text(), server_default='good', nullable=False, comment='SCADA quality flag (good/estimated/suspect)'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When GridCast stored the row'),
    sa.ForeignKeyConstraint(['zone_id'], ['ref.zones.zone_id'], name=op.f('fk_demand_readings_zone_id_zones')),
    sa.PrimaryKeyConstraint('zone_id', 'ts', name=op.f('pk_demand_readings')),
    schema='raw',
    comment='One-minute zone demand from the grid telemetry historian'
    )
    op.create_table('plan_intervals',
    sa.Column('plan_id', sa.UUID(), nullable=False, comment='Owning plan'),
    sa.Column('zone_id', sa.Text(), nullable=False, comment='Zone'),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False, comment='Hour'),
    sa.Column('forecast_load_mw', sa.Double(), nullable=False, comment='Expected load (p50)'),
    sa.Column('reserve_mw', sa.Double(), nullable=False, comment='Operating reserve (p90 - p50 + margin)'),
    sa.Column('scheduled_generation_mw', sa.Double(), nullable=False, comment='Generation to schedule'),
    sa.ForeignKeyConstraint(['plan_id'], ['planning.dispatch_plans.plan_id'], name=op.f('fk_plan_intervals_plan_id_dispatch_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['ref.zones.zone_id'], name=op.f('fk_plan_intervals_zone_id_zones')),
    sa.PrimaryKeyConstraint('plan_id', 'zone_id', 'interval_start', name=op.f('pk_plan_intervals')),
    schema='planning',
    comment='Per-zone hourly schedule within a plan'
    )
    # ### end Alembic commands ###
    _grants()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_intervals', schema='planning')
    op.drop_table('demand_readings', schema='raw')
    op.drop_table('forecast_validations', schema='quality')
    op.drop_index(op.f('ix_dispatch_plans_published_at'), table_name='dispatch_plans', schema='planning')
    op.drop_table('dispatch_plans', schema='planning')
    op.drop_index(op.f('ix_forecasts_zone_id_target_ts'), table_name='forecasts', schema='ml')
    op.drop_table('forecasts', schema='ml')
    op.drop_table('forecast_features', schema='features')
    op.drop_table('zones', schema='ref')
    op.drop_table('weather_observations', schema='raw')
    op.drop_index(op.f('ix_weather_forecasts_station_id_valid_at_issued_at'), table_name='weather_forecasts', schema='raw')
    op.drop_table('weather_forecasts', schema='raw')
    op.drop_index(op.f('ix_model_events_at'), table_name='model_events', schema='ml')
    op.drop_table('model_events', schema='ml')
    op.drop_table('model_aliases', schema='ml')
    op.drop_index(op.f('ix_forecast_runs_created_at'), table_name='forecast_runs', schema='ml')
    op.drop_table('forecast_runs', schema='ml')
    op.drop_table('weather_stations', schema='ref')
    op.drop_table('weather_providers', schema='ref')
    op.drop_index(op.f('ix_ingestion_batches_dataset_started_at'), table_name='ingestion_batches', schema='raw')
    op.drop_table('ingestion_batches', schema='raw')
    op.drop_index(op.f('ix_check_results_check_name_checked_at'), table_name='check_results', schema='quality')
    op.drop_table('check_results', schema='quality')
    op.drop_table('models', schema='ml')
    op.drop_index(op.f('ix_feature_runs_created_at'), table_name='feature_runs', schema='features')
    op.drop_table('feature_runs', schema='features')
    # ### end Alembic commands ###
    for schema in reversed(list(SCHEMAS)):
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE")
